int pin1 = 4;
int pin2 = 5;
int pin3 = 6;
int pin4 = 7;
int pin5 = 8;
int pin6 = 9;

int buttonPin = 3;
int delay_num = 1600;
int flag = 0;

void setup() {
  // put your setup code here, to run once:
   pinMode(pin1, OUTPUT);
   pinMode(pin2, OUTPUT);
   pinMode(pin3, OUTPUT);
   pinMode(pin4, OUTPUT);
   pinMode(pin5, OUTPUT);
   pinMode(pin6, OUTPUT);

   pinMode(buttonPin, INPUT_PULLUP);
}

void loop() {

  if (digitalRead(buttonPin) == LOW && flag == 0) 
    flag = 1;

  if( flag == 0)
    return;
  
  // put your main code here, to run repeatedly:
  digitalWrite(pin1, HIGH); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, HIGH); 
  digitalWrite(pin6, HIGH); 
  delay(delay_num);  

  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  
  digitalWrite(pin1, HIGH); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, HIGH); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
//중임중임
  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
//무황무황
  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, HIGH); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, HIGH); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
//태황태무임
  
  digitalWrite(pin1, HIGH); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, HIGH); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
//중임중임 

  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
//무황무황
  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, HIGH); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, HIGH); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  //태황무임중임
  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  //무황무무
  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, HIGH); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, HIGH); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, HIGH); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, HIGH); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  //중중중태황
  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, HIGH); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, HIGH); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  //태황태무임
  
  digitalWrite(pin1, HIGH); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  digitalWrite(pin1, HIGH); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  //중임중임
  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  //무황무황

  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, HIGH); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, HIGH); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, HIGH); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  //태황무임중임

    digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, HIGH); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  delay(delay_num);
  //무황무무

  
  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, HIGH); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 

  delay(delay_num);

  digitalWrite(pin1, LOW); 
  digitalWrite(pin2, LOW); 
  digitalWrite(pin3, LOW); 
  digitalWrite(pin4, LOW); 
  digitalWrite(pin5, LOW); 
  digitalWrite(pin6, LOW); 
  
  flag = 0;
}
